version: '3.8'

services:
  redroid:
    image: redroid/redroid:12.0.0_64only-latest
    container_name: redroid12
    privileged: true
    ports:
      - "5555:5555"
    volumes:
      - ~/data:/data
    restart: unless-stopped

  manager:
    build: .
    container_name: tg-manager
    network_mode: "host"
    volumes:
      - ./sessions:/app/sessions
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - ANDROID_DEVICE=localhost:5555
    depends_on:
      - redroid
    restart: unless-stopped
    mem_limit: 512m